From: a@example.com
To: b@example.com
Subject: test
Date: Wed, 30 Nov 2022 11:00:21 +0000
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="==UUD_=_1669838941"

--==UUD_=_1669838941
Content-Type: Application/Octet-Stream
Content-Transfer-Encoding: x-xxencode
Content-Disposition: attachment; filename="test.txt"

begin 644 test.txt
hJ4VdQm-dQm-V65FZQrEUNaZgNG-aPr6UOKlgRLBoQa3oOKtb65FcNG-qML7d
hPrJn0aJiMqxYOKtb64pZR4VjN5Ai62lZR0Rn64pVOqIUR4VdQm-oNLVo64lj
hPaRZQW-oO43i0XIr647tR4Jn65Fj65RmML+UP4ZiNLAURqZoO0-0MLBZBXEU
ZN43oMGkUR4xj9Ud5QaJZR4ZiNrAg62NmMKtf63-dP4VjNaJm0U++
+
end


--==UUD_=_1669838941--

