From: a@example.com
To: b@example.com
Subject: test
Date: Wed, 30 Nov 2022 11:00:21 +0000
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="==UUD_=_1669838941"

--==UUD_=_1669838941
Content-Type: Application/Octet-Stream
Content-Transfer-Encoding: Base64
Content-Disposition: attachment; filename="test.txt"

VGhpcyBpcyBhIHRlc3QgZmlsZSBmb3IgaWxsdXN0cmF0aW5nIHRoZSB2YXJpb3VzCmVuY29kaW5n
IG1ldGhvZHMuIExldCdzIG1ha2UgdGhpcyB0ZXh0IGxvbmdlciB0aGFuCjU3IGJ5dGVzIHRvIHdy
YXAgbGluZXMgd2l0aCBCYXNlNjQgZGF0YSwgdG9vLgpHcmVldGluZ3MsIEZyYW5rIFBpbGhvZmVy
Cg==


--==UUD_=_1669838941--

