name: Run CI tests
on:
- push
- pull_request

jobs:
  runci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: apt-get update
      - run: apt-get install -y build-essential autoconf
      - run: ./runci.sh
